### ISSUE TITLE
Async Serial source?

### ISSUE THREAD

**Issue by DieHertz** [saleae/AnalyzerSDK#14]
I would like to write some high-level protocol analyzers which are encapsulated into a serial transport, but there's no open `Async Serial` analyzer source to inherit from.
Could you release it's source code or I have to implement Serial parsing from scratch?

**Comment by Marcus10110** [comment]
You can download the source code to all of our analyzers, including the Async Serial analyzer, on our support site here:
https://support.saleae.com/hc/en-us/articles/115005987726-Protocol-Analyzer-SDK

We're going to get these migrated to individual github repos in the future - we're working on build system improvements now, which will include this migration. In the meantime just download the source code there, and use the the Sample Analyzer repo here:
https://github.com/saleae/SampleAnalyzer

If you need any help getting it setup and building, let me know and I can provide instructions (also include what platform you use)

We'll be making the setup process significantly easier when we migrate the analyzers to github.

Please be sure to rename the analyzer so that it does not conflict with the stock async analyzer. You will want to make sure the output library name is different, and the string returned by `SerialAnalyzer::GetAnalyzerName` and `GetAnalyzerName` in SerialAnalyzer.cpp are updated.

**Comment by DieHertz** [comment]
Thank you, I have some experience writinf analyzers, just wanted to inherit your serial implementation

**Comment by DieHertz** [comment]
Although my analyzer will be of limited use to outside public, I will release it :-)
It's for parsing common Radio Control receiver protocols, SBUS and CRSF.
