### ISSUE TITLE
Compile errors on linux due to path

### ISSUE THREAD

**Issue by brycenesbitt** [saleae/AnalyzerSDK#3]
I downloaded the SDK from http://support.saleae.com/hc/en-us/articles/208667926-Protocol-Analyzer-SDK
and immediately got a compile error.  The thing on Linux is looking in the wrong path.  Here's a patch:

```
*** v_build_analyzer.py	2017-05-11 11:02:51.023777648 -0700
--- build_analyzer.py	2017-05-11 11:05:58.541376293 -0700
***************
*** 39,44 ****
  
  #specify the search paths/dependencies/options for gcc
! include_paths = [ "../include" ]
! link_paths = [ "../lib" ]
  link_dependencies = [ "-lAnalyzer" ] #refers to libAnalyzer.dylib or libAnalyzer.so
  
--- 39,44 ----
  
  #specify the search paths/dependencies/options for gcc
! include_paths = [ "include" ]
! link_paths = [ "lib" ]
  link_dependencies = [ "-lAnalyzer" ] #refers to libAnalyzer.dylib or libAnalyzer.so
  
***************
*** 47,50 ****
--- 47,51 ----
  
  #loop through all the cpp files, build up the gcc command line, and attempt to compile each cpp file
+ print("Bryce: Working directory " + os.getcwd())
  for cpp_file in cpp_files:

```

**Comment by Marcus10110** [comment]
The old analyzer SDK download from the support site is pretty out dated, so I've updated the page to make it clear that the official sample analyzer project can be found here:
https://github.com/saleae/SampleAnalyzer
On Linux, it builds out of the box, although for x64 systems, you need to rename the libAnalyzer64.so file. I would like to get that handled automatically.
I'm going to close this issue, since it should be moot now that the old copy from the support site is depreciated.

**Comment by david-drinn** [comment]
To clarify, when building on Linux on x64 systems, do the following - as quoted from the `AnalyzerSDK/lib/readme.txt`:

> If you're on Linux 64-bit, remove libAnalyzer.so, and then rename libAnalyzer64.so to libAnalyzer.so
